apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 5m
  chart:
    spec:
      chart: opencost
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1