apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2