apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: solr
      version: '0.8.0'
      sourceRef:
        kind: HelmRepository
        name: solr
        namespace: default
      interval: 1m
  values:
    replicaCount: 1