apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: imageupdateautomation
  namespace: nginx
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository # the only valid value, but good practice to be explicit here
    name: flux-system
    namespace: flux-system
  git:
    commit:
      messageTemplate: |
        Automated image update by Flux
        
        [ci skip] 