---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx-repo
  namespace: nginx
spec:
  image: nginx
  interval: 1h
  provider: generic
  secretRef:
    name: dockerhub-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-auth
  namespace: nginx
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjoge30sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9