apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-flux
  namespace: default
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/MaximilianHaller/Flux_kustomize_helm.git